[project]
name = "order-generator"
version = "0.1.0"
description = "Service order producer over Kafka network"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.1",
    "pydantic>=2.11.3",
    "confluent-Kafka>=0.9.2"
]
